BASE_URL: 'https://test-automation-dojo.kloia.com'
HOME: '/'
INPUT_PATH: '/input'
CHECKBOX_PATH: '/checkbox'
DROPDOWN_PATH: '/dropdown'
HOVER_PATH: '/hovers'
REDIRECT_LINK_PATH: '/redirect-link'
BUTTON_PATH: '/buttons'
DATE_PICKER_PATH: '/datepicker'
FILE_UPLOAD_PATH: '/fileupload'